### ISSUE TITLE
Fails to build because it requires RocksDB to be build with `-fPIC`

### ISSUE THREAD

**Issue by roncemer** [Photonios/rocksdb-php#4]
With the latest rocksdb, I get this error when building rocksdb-php:

g++ -std=c++11 -fPIC -shared src/*.cpp -lrocksdb -lpthread -lrt -lsnappy -lgflags -lz -lbz2 -lphpcpp -lmemenv -I./src/include -o bin/rocksdb_php.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/librocksdb.a(db_impl.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/librocksdb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by Photonios** [comment]
Issue should be resolved now. You have to compile RocksDB with `-fPIC` now. I've updated the README on how to do that.

I've also fixed the `Makefile` to no longer link to `libmemenv`, because it appears that this is no longer necessary.

Thanks for reporting it!

Can you please verify that it builds now so I can close the issue?

**Comment by janisz** [comment]
Why `-fPIC` is now necessary?
